### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by manos2400** [manos2400/db-project-92#2]
### Library Manager
- [x] Ability to add books
- [x] Ability to edit books
- [x] Ability to search for a specific user's reservations/loans
- [x] Ability to register a loan without reservation
- [x] #3
