### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by manos2400** [manos2400/db-project-92#4]
### Admin Page

- [x] Create new Schools
- [x] Edit Existing School
- [x] Create and Edit Manager users
- [x] Approve Manager applications
- [x] Backup and Restore the database 
- [x] 3.1.1 
- [x] 3.1.2
- [x] 3.1.3
- [x] 3.1.4
- [x] 3.1.5
- [x] 3.1.6
- [x] 3.1.7
